version: '3'

services:
  postgres:
    container_name: postgres_gerente
    image: postgres
    environment:
      POSTGRES_DB: bantads-gerente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - gerente-network
    restart: always

  gerente:
    build: .
    image: bantads_gerente
    restart: on-failure
    container_name: bantads_gerente_container
    command: docker run -p 8080:8080 bantads_gerente
    volumes:
      - .:/app
      - static_data:/app/static
    networks:
      - gerente-network
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres:
  static_data:

networks:
  gerente-network:
    external: false